"""tabela JogadorGamer

Revision ID: 4cd58c15661b
Revises: 641168213e11
Create Date: 2025-10-27 01:31:01.409848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd58c15661b'
down_revision = '641168213e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubes')
    op.drop_table('Clube')
    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.alter_column('mandante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('visitante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'clube', ['mandante_id'], ['id'])
        batch_op.create_foreign_key(None, 'clube', ['visitante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('visitante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mandante_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('Clube',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('estadio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fundacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('escudo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('vitorias', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empates', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('derrotas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gols_pro', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gols_contra', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Clube_pkey')
    )
    op.create_table('clubes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fundacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estadio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('escudo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('vitorias', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empates', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('derrotas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gols_pro', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gols_contra', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clubes_pkey')
    )
    # ### end Alembic commands ###
