"""Inicial-2

Revision ID: 641168213e11
Revises: 
Create Date: 2025-10-23 10:43:43.218035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641168213e11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clube', schema=None) as batch_op:
        batch_op.alter_column('fundacao',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Clube', schema=None) as batch_op:
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('fundacao',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
