"""tabela JogadorGamer3

Revision ID: e398ad452e54
Revises: 4cd58c15661b
Create Date: 2025-10-27 02:12:20.999524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e398ad452e54'
down_revision = '4cd58c15661b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JogadorGamer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positio', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JogadorGamer', schema=None) as batch_op:
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')
        batch_op.drop_column('positio')

    # ### end Alembic commands ###
